name: Publish package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch(1.0.x), minor(1.x.0), major(x.0.0), prepatch, preminor, premajor(x.0.0-0), prerelease"
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Action setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      # Configure Git Actions author
      # @link https://github.com/orgs/community/discussions/26560
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      # Bump package version
      - name: Bump release version
        if: startsWith(github.event.inputs.release-type, 'pre') != true
        run: |
          echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Commit new package version
      - name: Commit package.json version change
        run: |
          git add "package.json"
          git commit -m "Update package.json ${{ env.NEW_VERSION }} release"

      # Run packages install
      - run: npm i

      # Tests
      #- run: npm run test-jsx
      #- run: npm run test-utilities

      # Publish to npm
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_CD_TOKEN }}

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin
